version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_deploy:
    commands:
      - echo "Creating adding stage $STAGE"
      # - mkdir .sst
      # - echo "$ENVIRONMENT" > .sst/stage
      # - cat .sst/stage
      - export SST_STAGE=$STAGE

  deploy:
    commands:
      - echo "Starting build process... stage- $SST_STAGE"
      - npx sst deploy
    on-failure: ABORT

  post_deploy:
    commands:
      - echo "Post-build steps running..."
      - echo "Checking if build failed and uploading logs if needed..."
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]; then
          cat .sst/log/sst.log
        fi
      - echo "Post-build phase complete."

# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 20  # Specify the runtime versions as needed
#     commands:
#       - echo "Installing dependencies..."
#       - npm install 

#   pre_sst_deploy:
#     commands:
#       - echo "Running pre-sst-deploy tasks..."
#       - # Add any pre-build commands you need


#   sst_deploy:  # Custom phase
#     commands:
#       - echo "Running custom phase tasks..."
#       - ./scripts/custom_script.sh  # Path to your custom script

#   post_sst_deploy:
#     commands:
#       - echo "Running sst-deploy tasks..."
#       - # Add any post-build commands you need


