/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "VisionAccountsAPI": {
      "type": "sst.aws.ApiGatewayV1"
      "url": string
    }
    "account": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
